### ISSUE TITLE
Wont work on device

### ISSUE THREAD

**Issue by netwrkx** [cowbell/ionic-geofence#19]
The program worked on browser but wouldnt work on my device.

it **stop at "Obtaining current location"...**

i also added this line of code to the manifest file but **couldn't get it to work**
uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" 
uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" 
uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" 

Can you help me with it

**Comment by tsubik** [comment]
What is the version of android on your device?

**Comment by netwrkx** [comment]
Android 6, Nexus 7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Tomasz SubikSent: Wednesday, 6 April 2016 17:37To: cowbell/ionic-geofenceReply To: cowbell/ionic-geofenceCc: Adebowale SamsonSubject: Re: [cowbell/ionic-geofence] Wont work on device (#19)What is the version of android on your device?

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by tsubik** [comment]
Thanks, so this is related to https://github.com/cowbell/cordova-plugin-geofence/issues/130. I'm working on it.

**Comment by netwrkx** [comment]
okay
