### ISSUE TITLE
getbound()

### ISSUE THREAD

**Issue by netwrkx** [cowbell/ionic-geofence#20]
how do i implement getbound() or is there any similar function that act as getbound()
[leafletjs.com](http://leafletjs.com/reference.html#latlngbounds)

var paths = {
        circle: {
            type: 'circle',
            radius: geofence.radius,
            latlngs: $scope.markers.marker,
            clickable: false
        }
    };

circleBounds = paths.getBounds()

Returns the LatLngBounds of the circle (created from bounds and coordinates of its children).

**Comment by tsubik** [comment]
I think this question should be posted on stackoverflow.
