### ISSUE TITLE
geofence circle  not show

### ISSUE THREAD

**Issue by Nagapandi** [cowbell/ionic-geofence#22]
Hi,
   i am trying to load a geofence in leaflet with google layer. It shows an exception in leaflet-src.js, "Cannot call method 'intersects' of undefined"
empty: function () {
        return this._radius && !this._renderer._bounds.intersects(this._pxBounds);
    }
please let me know the reason.

**Comment by tsubik** [comment]
This is a leaflet related problem, please look up for the answer on StackOverflow.
