### ISSUE TITLE
Doesn't compile with latest tool chain

### ISSUE THREAD

**Issue by siddiq** [cowbell/ionic-geofence#26]
$ ionic info

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.8.6 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by siddiq** [comment]
![screen shot 2016-10-06 at 9 27 22 pm](https://cloud.githubusercontent.com/assets/1002327/19163162/fb4a592c-8c0b-11e6-97c3-e1cf9b112723.png)

**Comment by tsubik** [comment]
I think this was the same problems as #24.
