### ISSUE TITLE
window.geofence is always undefined

### ISSUE THREAD

**Issue by fnokeke** [cowbell/ionic-geofence#29]
Hi, 

Running `ionic serve` shows everything working just fine. However, on closer look, I realized that `$window.geofence` is always `undefined` (that means `GeofencePluginMock` is used instead). 

I tried installing the cordova plugin directly into the ionic app:`cordova plugin add cordova plugin add cordova-plugin-geofence` but geofence is still undefined. 

Any pointers will be helpful. 
Thanks

**Comment by tsubik** [comment]
`ionic serve` is running this application in browser environment just for testing purposes. It is using plugin mock to easily test application workflow. Cordova plugin is installed only for `ios`, `android` and `wp` environments.
