### ISSUE TITLE
ionic-geofence notification is not working on iOS device/xcode simulator

### ISSUE THREAD

**Issue by laksasi** [cowbell/ionic-geofence#31]
Hi ,

Ionic-geofence notifications are working in Android platform but not working in iOS platform. Notifications are not working on xcode simulator( ios 10.2) and iPhone 7/7s device . Location service is working in both platforms but notifications are not showing up in ios.

**Comment by tsubik** [comment]
Just checked, and looks like works fine for me. You can check XCode logs while debugging application.
