### ISSUE TITLE
Application did not work

### ISSUE THREAD

**Issue by thomas-tran** [cowbell/ionic-geofence#6]
I tried this app in galaxy note 2, 3 and ios 7 and the there is no notification shown when near the pre define perimeters.

**Comment by nez** [comment]
+1 had the same problem

**Comment by fenwick67** [comment]
:+1: this also happens to me, using a Nexus 7 on Android 5.0.1.

**Comment by fenwick67** [comment]
I thought it wasn't working for me too, but making the geofence larger solved my issues (Nexus 7), I think I was never in the geofence to begin with so it never triggered (I started with the smallest allowed).

**Comment by kennygfunk** [comment]
When I click tests it redirects to a url that I don't have. Am I missing something?

This directory doesn't exist: http://localhost:8100/cdvtests/index.html

**Comment by tsubik** [comment]
Thank @kennygfunk I forgot to re-add cordova plugin test framework. It should be fine now. @thomas-tran @nez any logcat logs will be appreciated.

**Comment by kennygfunk** [comment]
Thanks @tsubik! I can get to the Cordova plugin test page now. 9 specs, 0 failures. Although I am still not getting any notifications. When I test on iOS 8.3 I am getting an error that I am missing the keyboard cordova plugin:

Error: undefined is not an object (evaluating '$window.cordova.plugins.Keyboard')

Not sure how much of an issue this is though. Also, nothing is happening when I test in the browser. No toaster notifications pop up or anything. I can't seem to get inside the $window.geofence if statement but the plugin is definitely there. Any advice on this? Next steps for troubleshooting? I have made a few ionic apps but I am still new at this and would love to get geofencing working on an app I am working on. Cheers

**Comment by tsubik** [comment]
I hope you found right solution.

**Comment by kennygfunk** [comment]
I did actually thanks @tsubik sorry I didn't write back

**Comment by Bekassyl** [comment]
@kennycrosby Hey, could you write short guide how did you solve the problem if you remember ofc

**Comment by Bekassyl** [comment]
@tsubik Thank you for creating such usefull plugin. Have u any ideas how to solve the problem? I run it in IonicView on IPhone and no notifications showing up
