### ISSUE TITLE
Failed to install geofence plugin

### ISSUE THREAD

**Issue by simpledev** [cowbell/ionic-geofence#7]
When I run this command 
    ionic platform add ios

    Failed to install 'com.cowbell.cordova.geofence':Error: Cannot find module 'cordova-   lib/src/plugman/platforms'

An idea ?

**Comment by tsubik** [comment]
Did you run `npm install` at first?

**Comment by tsubik** [comment]
Maybe problem is because you are using cordova 5.0, project is not tested with cordova 5.0 yet.

**Comment by simpledev** [comment]
Ok thanks. Do you think maybe the plugin will be available for cordova 5.0 ?

**Comment by tsubik** [comment]
It is now :). Look at the latest [changes](https://github.com/cowbell/cordova-plugin-geofence/blob/master/CHANGELOG.md).

**Comment by simpledev** [comment]
Thank you so much, it's the best geofencing plugin.
