### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by sbegh** [cowbell/ionic-geofence#9]
Hi !
First of all : Thanks for this example and "bravo" !
I have just a question, i don't know if it is an issue, but...
When i inspect Local Storage in debug mode, after put a single geofence, i have got the same data twice ... Is it normal and could you explain why ?
Thanks for reply
sbeGhen
![geo](https://cloud.githubusercontent.com/assets/10943606/8143548/2e8ac5c2-11b2-11e5-9777-c0b2748da9f1.JPG)

**Comment by tsubik** [comment]
Hey @sbegh you can append any data you want to `notification.data`. This data will be passed into your application on notification click. In this example app I am just using copy of geofence object as notification data.
